# -*- coding: utf-8 -*-
"""Modelling_notebook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qdoUPZNl93x2Eb-BcXWNwSzr5TUGKkja

## 1. Install and import Libraries
"""

# 1a. Install liraries
!pip install pandas numpy scikit-learn tensorflow sentence-transformers \
transformers torch gradio deep-translator langdetect matplotlib datasets nltk tf-keras flask openpyxl faiss-cpu gradio

# Import libraries
import glob
import os
import pandas as pd
from collections import Counter
import re
import nltk
from nltk.corpus import stopwords
import unicodedata
import random
import tensorflow as tf
from collections import defaultdict
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

from torch import nn
from torch.utils.data import DataLoader, TensorDataset, random_split

from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.metrics import accuracy_score, f1_score, classification_report
from tensorflow.keras.initializers import GlorotUniform
from sklearn.preprocessing import normalize

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sentence_transformers import InputExample

from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Embedding, LSTM, GRU, Bidirectional, GlobalMaxPooling1D

from transformers import AutoTokenizer, AutoModelForSequenceClassification, AutoModel
from transformers import Trainer, TrainingArguments
import torch
from sentence_transformers import SentenceTransformer, util
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM, pipeline

from deep_translator import GoogleTranslator
from sentence_transformers import SentenceTransformer
import numpy as np

from langdetect import detect

import gradio as gr
from flask import Flask, request
from fastapi import FastAPI
from pydantic import BaseModel
import json

"""## 2. Load data from Github"""

#2a Fetch excel files from github

# Clean
!rm -rf /content/sepedi_rabies_data/

# Download
!wget -O data.zip "https://github.com/MuphulusiDzivhani/Rabies-chatbot/raw/main/Nicd%20data.zip"

# Unzip
!unzip -o data.zip -d /content/sepedi_rabies_data/

import requests

url = "https://github.com/MuphulusiDzivhani/Rabies-chatbot/raw/main/Nicd%20data.zip"
output_path = "data.zip"

response = requests.get(url)

with open(output_path, "wb") as f:
    f.write(response.content)

print("Download complete:", output_path)

# 2b. Load data
data_path = "/content/sepedi_rabies_data/Nicd data/"
#all_files = glob.glob(data_path + "*.xlsx")
all_files = glob.glob(data_path + "*.xlsx")
# Training: only v2
train_files = [f for f in all_files if "_v2" in f and "test" not in f.lower()]

# Testing
test_file = [f for f in all_files if "test question" in f.lower()]

print("Train:", len(train_files), "Test:", len(test_file))

"""## 3. Intent Classifier (train data)
Will also add top ten common words per topic for each language.

This eleminates stops words
"""

nltk.download('stopwords')

# ---------------------------
# Stopwords
# ---------------------------
sepedi_stopwords = set([
    'ke','go','le','ya','ba','e','o','sa','ka','tša','tše','mo',
    'ga','gore','ye','di','na','la','bo','ge','se','bja','wa'
])

english_stopwords = set(stopwords.words('english'))

# ---------------------------
# Text cleaning (VERY IMPORTANT)
# ---------------------------
def clean_text(text):
    text = str(text).lower().strip()
    text = unicodedata.normalize('NFKD', text).encode('ascii', 'ignore').decode('utf-8')
    text = re.sub(r'[^a-zA-Z\s]', ' ', text)
    text = re.sub(r'\s+', ' ', text)
    return text.strip()

# ---------------------------
# Topic extractor
# ---------------------------
def topic(filename):
    tag = filename.replace(".xlsx", "").lower()
    tag = tag.replace("_sepedi_v2", "")
    tag = tag.replace("rabies_", "")
    return tag

# ---------------------------
# Top words function
# ---------------------------
def get_top_distinct_words(text_list, stopwords_set, top_n=10):
    words = []
    for text in text_list:
        for word in text.split():
            if len(word) > 1 and word not in stopwords_set:
                words.append(word)

    counter = Counter(words)
    return [w for w, _ in counter.most_common(top_n)]

# ---------------------------
# Containers
# ---------------------------
sepedi_to_english = {}
english_to_sepedi = {}

texts_by_topic_sepedi = defaultdict(list)
texts_by_topic_english = defaultdict(list)

# FINAL chatbot corpus
corpus = []
answers = []
eng_answers = []
qa_pairs = []
topics = []
questions = []

# ---------------------------
# Process training files
# ---------------------------
for file in train_files:
    df = pd.read_excel(file)
    df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")

    tag = topic(os.path.basename(file))

    for _, row in df.iterrows():

        q_sep = row.get('question_sepedi')
        q_eng = row.get('question_english')
        a_sep = row.get('answer_sepedi')
        a_eng = row.get('answer_english')

        # ---------------------------
        # Clean
        # ---------------------------
        if pd.notna(q_sep):
            q_sep = clean_text(q_sep)
            questions.append(q_sep)
        if pd.notna(q_eng):
            q_eng = clean_text(q_eng)
            questions.append(q_eng)
        if pd.notna(a_sep):
            a_sep = clean_text(a_sep)
            answers.append(a_sep)
        if pd.notna(a_eng):
            a_eng = clean_text(a_eng)
            answers.append(a_eng)

        # ---------------------------
        # Translation dictionaries
        # ---------------------------
        if q_sep and a_sep:
            qa_pairs.append({
                "questions": [q_sep, q_eng],
                "answer": a_sep
            })
        if q_sep and q_eng:
            sepedi_to_english[q_sep] = q_eng

        if a_eng and a_sep:
            english_to_sepedi[a_eng] = a_sep

        # ---------------------------
        # Store per-topic texts
        # ---------------------------
        if q_sep:
            texts_by_topic_sepedi[tag].append(q_sep)

        if q_eng:
            texts_by_topic_english[tag].append(q_eng)

        # ---------------------------
        # Build chatbot corpus
        # ---------------------------
        if q_eng and a_eng:
            corpus.append(q_eng)
            eng_answers.append(a_eng)
            topics.append(tag)

# ---------------------------
# Top words per topic
# ---------------------------
top_words_per_topic_sepedi = {
    t: get_top_distinct_words(txts, sepedi_stopwords)
    for t, txts in texts_by_topic_sepedi.items()
}

top_words_per_topic_english = {
    t: get_top_distinct_words(txts, english_stopwords)
    for t, txts in texts_by_topic_english.items()
}
sepedi_corpus = list(sepedi_to_english.keys())
english_corpus = list(sepedi_to_english.values())
# ---------------------------
# Final checks
# ---------------------------
print("Corpus size:", len(corpus))
print("Topics:", set(topics))
print("Sepedi→English pairs:", len(sepedi_to_english))
print("English→Sepedi pairs:", len(english_to_sepedi))

print("\nTop words (Sepedi):")
for k, v in top_words_per_topic_sepedi.items():
    print(k, ":", v)

print("\nTop words (English):")
for k, v in top_words_per_topic_english.items():
    print(k, ":", v)

"""### 3b. TEST DATA"""

test_data = []

test_file = [f for f in all_files if "test" in f.lower() and "question" in f.lower()][0]

xls = pd.ExcelFile(test_file)

for sheet in xls.sheet_names:
    print("Processing:", sheet)

    df = pd.read_excel(test_file, sheet_name=sheet)
    df.columns = df.columns.str.lower().str.strip().str.replace(" ", "_")

    # ---------------------------
    # FIX topic naming (match training)
    # ---------------------------
    topic_name = sheet.lower().replace("rabies_", "")

    # ---------------------------
    # Select only question columns
    # ---------------------------
    question_cols = [c for c in df.columns if "sepedi" in c]

    for _, row in df.iterrows():
        for col in question_cols:
            if pd.notna(row[col]):

                q = clean_text(row[col])
                test_data.append({
                    "sep_q": q,
                    "en_q": row["english"],
                    "true_topic": topic_name
                })

print("Total test samples:", len(test_data))
print(test_data)

# quick translation test using loaded train data
english_to_sepedi_q = {v: k for k, v in sepedi_to_english.items()}
sample = list(sepedi_to_english.keys())[10]

print("Sepedi:", sample)
print("English:", sepedi_to_english[sample])

"""## 4. PREPROCESSING"""

def set_seed(seed=42):
    os.environ['PYTHONHASHSEED'] = str(seed)
    os.environ['TF_DETERMINISTIC_OPS'] = '1'

    random.seed(seed)
    np.random.seed(seed)
    tf.random.set_seed(seed)

set_seed(42)

# Encode topics
le = LabelEncoder()
y = le.fit_transform(topics)

# Tokenize text
max_words = 8000
tokenizer = Tokenizer(num_words=max_words, oov_token="<OOV>")
tokenizer.fit_on_texts(corpus)

X = tokenizer.texts_to_sequences(corpus)

# Padding
max_len = 40
X = pad_sequences(X, maxlen=max_len, padding='post')

print(" Shape (Sepedi + English Quesions):", X.shape)

def custom_train_test_split(X, y, test_size_per_class=2, random_state=42):
    np.random.seed(random_state)

    train_idx = []
    test_idx = []

    classes = np.unique(y)

    for cls in classes:
        cls_idx = np.where(y == cls)[0]
        np.random.shuffle(cls_idx)

        test_samples = cls_idx[:test_size_per_class]
        train_samples = cls_idx[test_size_per_class:]

        test_idx.extend(test_samples)
        train_idx.extend(train_samples)

    return (
        X[train_idx], X[test_idx],
        y[train_idx], y[test_idx]
    )

# Train/test split
X_train, X_val, y_train, y_val = custom_train_test_split(
    X, y, test_size_per_class=2, random_state=42
)

"""## 5. BUILD MODELS"""

vocab_size = 8000
embedding_dim = 128
num_classes = len(set(y))
initializer = GlorotUniform(seed=42)

def build_ann():
    return Sequential([
        Embedding(vocab_size, embedding_dim, input_length=40),
        GlobalMaxPooling1D(),
        Dense(64, activation='relu', kernel_initializer=initializer),
        Dense(num_classes, activation='softmax', kernel_initializer=initializer)
    ])

def build_lstm():
    return Sequential([
        Embedding(vocab_size, embedding_dim, input_length=40),
        LSTM(64, kernel_initializer=initializer, recurrent_initializer=initializer),
        Dense(num_classes, activation='softmax', kernel_initializer=initializer)
    ])

def build_bilstm():
    return Sequential([
        Embedding(vocab_size, embedding_dim, input_length=40),
        Bidirectional(LSTM(64, kernel_initializer=initializer, recurrent_initializer=initializer)),
        Dense(num_classes, activation='softmax', kernel_initializer=initializer)
    ])

def build_gru():
    return Sequential([
        Embedding(vocab_size, embedding_dim, input_length=40),
        GRU(64, kernel_initializer=initializer, recurrent_initializer=initializer),
        Dense(num_classes, activation='softmax', kernel_initializer=initializer)
    ])

def build_bigru():
    return Sequential([
        Embedding(vocab_size, embedding_dim, input_length=40),
        Bidirectional(GRU(64, kernel_initializer=initializer, recurrent_initializer=initializer)),
        Dense(num_classes, activation='softmax', kernel_initializer=initializer)
    ])

"""## 6. TRAIN & EVALUATE DEEP LEARNING MODELS"""

dl_models = {
    "ANN": build_ann(),
    "LSTM": build_lstm(),
    "BiLSTM": build_bilstm(),
    "GRU": build_gru(),
    "BiGRU": build_bigru()
}
results = {}
dl_results = {}
trained_models = {}

for name, model in dl_models.items():
    model.compile(
        loss='sparse_categorical_crossentropy',
        optimizer='adam',
        metrics=['accuracy']
    )

    model.fit(
        X_train, y_train,
        validation_data=(X_val, y_val),
        epochs=10,
        batch_size=8,
        verbose=0,
        shuffle=False
    )
    preds = model.predict(X_val, verbose=0).argmax(axis=1)

    acc = accuracy_score(y_val, preds)
    f1 = f1_score(y_val, preds, average='weighted')



    results[name] = {
        "accuracy": round(acc, 3),
        "f1": round(f1, 3)
    }
    #dl_results[name] = {"accuracy": acc, "f1": f1}
    #trained_models[name] = model
#results

import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

# Confusion matrix
cm = confusion_matrix(y_val, preds)

# Plot
disp = ConfusionMatrixDisplay(confusion_matrix=cm)
disp.plot()

plt.title("Confusion Matrix: Actual vs Predicted")
plt.show()

from sklearn.metrics import classification_report

print(classification_report(y_val, preds))

import pandas as pd
import matplotlib.pyplot as plt

df_results = pd.DataFrame(results).T
df_results.plot(kind='bar')
plt.title("Model Comparison")
plt.show()

def predict_dl(model, text):
    seq = tokenizer.texts_to_sequences([text])
    pad = pad_sequences(seq, maxlen=max_len)

    pred = model.predict(pad, verbose=0)
    return le.inverse_transform([np.argmax(pred)])[0]

"""##  7. TRANSFORMER EMBEDDING MODEL
Sentence transformers
*   multingual-mpet-base-V2
*   




"""

#fix labels and standardise across dataset

CANONICAL_LABELS = {
    "topic1_epidemiology_surveillance": "epidemiology",
    "topic2_prevention_control": "prevention",
    "topic3_virology_diagnosis": "diagnosis",
    "topic4_case_definition_clinical": "clinical",
    "topic5_geography_risk_areas": "risk",
    "topic5_geographical_risk": "risk",
    "topic6_public_awareness_education": "awareness",
    # Add new mappings for test data inconsistencies
    "topic1_epidemiology_surv": "epidemiology",
    "topic2_prevention": "prevention",
    "topic3_virology": "diagnosis",
    "topic4_clinical": "clinical",
    "topic6_awareness": "awareness"
}

def clean_label(label):
    label = str(label).lower().strip().replace(" ", "_")
    return CANONICAL_LABELS.get(label, label)

topics_clean = [clean_label(t) for t in topics]

# Initialize test_labels from test_data and clean them
test_labels = [item.get("true_topic") for item in test_data]
test_labels = [clean_label(t) for t in test_labels]

print("TRAIN LABELS:", sorted(set(topics_clean)))
print("TEST LABELS:", sorted(set(test_labels)))

# last check
assert set(test_labels) == set(topics_clean), "Label mismatch still exists!"

#Embedding model retrival
embed_model = SentenceTransformer(
    "sentence-transformers/paraphrase-multilingual-mpnet-base-v2"
)
kb_embeddings = embed_model.encode(corpus, convert_to_numpy=True)
kb_answers = [clean_text(a) for a in eng_answers]

#Translation model (NLLB)
model_name = "facebook/nllb-200-distilled-600M"

tokenizer = AutoTokenizer.from_pretrained(model_name)
trans_model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

# Fallback generator (FLAN-T5) for sepedi - english translation
from transformers import pipeline

generator = pipeline(
    "text-generation",
    model="google/flan-t5-base"
)
generator("Translate English to Sepedi", max_new_tokens=50)

def translate_to_english(text):
    tokenizer.src_lang = "nso_Latn"

    inputs = tokenizer(text, return_tensors="pt")

    outputs = trans_model.generate(
        **inputs,
        forced_bos_token_id=tokenizer.convert_tokens_to_ids("eng_Latn")
    )

    return tokenizer.decode(outputs[0], skip_special_tokens=True)

def retrieve_answer(query):
    q_emb = embed_model.encode(query, convert_to_tensor=True)
    scores = util.cos_sim(q_emb, kb_embeddings)[0]

    best_idx = int(scores.argmax())
    best_score = float(scores[best_idx])

    return best_idx, best_score

# TOP-K RETRIEVAL (for hybrid fallback)
def retrieve_top_k(query, k=3):
    q_emb = embed_model.encode(query, convert_to_tensor=True)
    scores = util.cos_sim(q_emb, kb_embeddings)[0]

    top_k = scores.topk(k)

    results = []
    for idx, score in zip(top_k.indices, top_k.values):
        results.append((corpus[int(idx)], kb_answers[int(idx)], float(score)))

    return results

# store new question and answers do the model can learn. For better retrival
import json
def store_new_qa(sepedi, english, answer):
    new_data = {
        "sepedi": sepedi,
        "english": english,
        "answer": answer
    }

    with open("qa_memory.json", "a", encoding="utf-8") as f:
        f.write(json.dumps(new_data) + "\n")

SIM_THRESHOLD = 0.75

def chatbot(sepedi_question):

    # 1. Translate ALWAYS
    english_q = translate_to_english(sepedi_question)

    if not english_q or english_q.strip() == "":
        english_q = sepedi_question

    # 2. Retrieve best match
    idx, score = retrieve_answer(english_q)

    # 3. High confidence → dataset answer
    if score >= SIM_THRESHOLD:
        return {
            "answer": kb_answers[idx],
            "source": "dataset",
            "score": score,
            "translated": english_q
        }

    # -----------------------------
    # 4. HYBRID FALLBACK (RAG)
    # -----------------------------
    top_k = retrieve_top_k(english_q, k=3)

    context = ""
    for q, a, s in top_k:
        context += f"Q: {q}\nA: {a}\n\n"

    prompt = f"""
Use the context below to answer the question.
If unsure, say you are not certain.

Context:
{context}

Question:
{english_q}
"""

    response = generator(prompt, max_length=200)[0]["generated_text"]

    answer = response

    # 5. Learn new QA
    if len(answer) > 10:
        store_new_qa(sepedi_question, english_q, answer)

    return {
        "answer": answer,
        "source": "hybrid",
        "score": score,
        "translated": english_q
    }

import torch
import numpy as np # Add numpy import for isinstance check

# Ensure kb_embeddings is a PyTorch tensor and on the correct device (cuda:0 as per error)
# Determine the device. The error indicated cuda:0 for one tensor.
# So we explicitly try to move kb_embeddings to cuda if available.
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Convert kb_embeddings (which is currently a numpy array as per kernel state)
# to a torch tensor and move it to the determined device.
if isinstance(kb_embeddings, np.ndarray):
    kb_embeddings = torch.from_numpy(kb_embeddings).to(device)

#Evaluation pipeline
results = []

for item in test_data[:50]:

    sepedi_q = item.get("sep_q")
    true_english = item.get("en_q")

    if not sepedi_q or not true_english:
        print("Skipping:", item)
        continue

    result = chatbot(sepedi_q)

    results.append({
        "sepedi": sepedi_q,
        "true_english": true_english,
        "translated": result.get("translated", ""),
        "source": result.get("source", ""),
        "score": result.get("score", 0),
        "topic": item.get("true_topic")
    })

# Retrive using similarity
similarities = []

for r in results:

    t1 = r["translated"]
    t2 = r["true_english"]

    if not t1 or not t2:
        continue

    emb1 = embed_model.encode(t1, convert_to_tensor=True)
    emb2 = embed_model.encode(t2, convert_to_tensor=True)

    sim = util.cos_sim(emb1, emb2).item()

    similarities.append(sim)

print("Valid samples:", len(similarities))

if len(similarities) > 0:
    print("Avg translation similarity:", np.mean(similarities))
else:
    print("No valid samples found")

print("Total results:", len(results))
print(results[:2])

print(translate_to_english("Rabies ke eng?"))

for r in results[:10]:
    print("translated:", repr(r.get("translated")))
    print("true_english:", repr(r.get("true_english")))
    print("----")

correct = 0

for r in results:
    if r["source"] == "dataset":
        correct += 1

accuracy = correct / len(results)

print("Retrieval Accuracy:", accuracy)

"""## 14. GRADIO UI"""

import gradio as gr

def gradio_chat(sepedi_question):
    result = chatbot(sepedi_question)

    return f"""
    Translated: {result['translated']}
    Score: {result['score']:.3f}
    Source: {result['source']}

    Answer:
    {result['answer']}
    """

interface = gr.Interface(
    fn=gradio_chat,
    inputs=gr.Textbox(lines=2, placeholder="Type Sepedi question here..."),
    outputs="text",
    title="Sepedi ↔ English Rabies Chatbot",
    description="Ask questions in Sepedi. Uses translation + semantic search."
)

interface.launch()

"""## 15. FACEBOOK INTEGRATION"""

from flask import Flask, request

app = Flask(__name__)

@app.route("/webhook", methods=["POST"])
def webhook():
    data = request.json

    user_message = data["message"]["text"]

    bot_response = chatbot_pipeline(user_message)

    return {"reply": bot_response}